// swift-tools-version:5.9
//
// Auto-generated by belotserkovtsev/Ladon .github/workflows/ios-release.yml.
// Each release commit here corresponds to one tagged release in
// belotserkovtsev/Ladon; the binaryTarget below points at the
// .xcframework.zip attached to that release. Do not edit by hand —
// the next release overwrites this file.

import PackageDescription

let package = Package(
    name: "Ladon",
    platforms: [
        .iOS(.v16),
    ],
    products: [
        .library(name: "Ladon", targets: ["Ladon"]),
    ],
    targets: [
        .binaryTarget(
            name: "Ladon",
            url: "https://github.com/belotserkovtsev/Ladon/releases/download/v0.6.0-rc1/Ladon.xcframework.zip",
            checksum: "911886b71dfc607a2a267932461c8e713caafab8bc46b861efdc5b0ba0f504dd"
        ),
    ]
)
